name: build
on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo Building...
      - name: Test
        run: echo Testing...
      - name: Scan
        run: echo Scan...
      - name: Package
        run: echo Package...
      - name: Publish
        uses: actions/upload-artifact@v2.3.1
        with:
          name: release
          path: .

  chain-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: TO DO
        run: echo TO DO..
            
    
