name: deploy-cd

on:
  workflow_run:
    workflows: [build]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Build succeeded - triggering deploy

        echo Artifact is at: ${{ github.event.workflow_run.artifacts_url }}
