name: Call me
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
    secrets:
      secretname:
        required: false

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greetings
      run: |
        echo "Hello imput parameter: ${{ github.inputs.name }}"
        echo "Hello secret: ${{ secrets.secretname }}"
        echo "Running in repo ${{ github.repository }}"
