name: Hello Actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.9.9'
      #     architecture: 'x64'

      - name: Fun with PIP
        shell: bash
        run: |
          pip3 install -r requirements.txt
          pip3 cache dir
          ls `pip3 cache dir`

      # - name: Local Composite Action Sample
      #   uses: ./hw-action
    
  # call_reuse:
  #   uses: dmckinstry/action-ch/.github/workflows/reuse.yml@main
  #   with:
  #     name: passed-in
      

